name: "CI"

on:
    pull_request:
    push:
        branches:
            - 'master'

env:
    fail-fast: true
    TZ: "Europe/Paris"

jobs:
    psalm:
        name: "Psalm (${{ matrix.php-version }})"

        runs-on: "ubuntu-latest"

        strategy:
            matrix:
                php-version:
                    - '8.0'

        steps:
            -
                name: "Checkout code"
                uses: "actions/checkout@v2"

            -
                name: "Install PHP"
                uses: "shivammathur/setup-php@v2"
                with:
                    coverage: "none"
                    extensions: "${{ env.REQUIRED_PHP_EXTENSIONS }}"
                    php-version: "${{ matrix.php-version }}"
                    tools: composer:v2

            -
                name: "Composer install"
                uses: "ramsey/composer-install@v1"
                with:
                    composer-options: "--no-scripts"

            -
                name: "Run Psalm"
                run: "vendor/bin/psalm"
    phpunit:
        name: "PHPUnit (${{ matrix.php-version }})"

        runs-on: "ubuntu-latest"

        strategy:
            matrix:
                php-version:
                    - '8.0'

        steps:
            -
                name: "Checkout code"
                uses: "actions/checkout@v2"

            -
                name: "Install PHP"
                uses: "shivammathur/setup-php@v2"
                with:
                    coverage: "none"
                    extensions: "${{ env.REQUIRED_PHP_EXTENSIONS }}"
                    php-version: "${{ matrix.php-version }}"
                    tools: composer:v2

            -
                name: "Composer install"
                uses: "ramsey/composer-install@v1"
                with:
                    composer-options: "--no-scripts"
            -
               name: "Setup git credentials"
               run: |
                   git config --global user.email "you@example.com"
                   git config --global user.name "Your Name"
            -
                name: "Run Maestro"
                run: "bin/maestro run example/pipeline/BasePipeline.php"

            -
                name: "Run PHPUnit"
                run: "vendor/bin/phpunit"
    docs:
        runs-on: ubuntu-latest
        steps:
            - 
                name: "Checkout"
                uses: actions/checkout@v1
            -
                name: "Install PHP"
                uses: "shivammathur/setup-php@v2"
                with:
                    coverage: "none"
                    php-version: "8.0"
                    tools: composer:v2

            -
                name: "Composer install"
                uses: "ramsey/composer-install@v1"
                with:
                    composer-options: "--no-scripts"

            -
                name: "Generate Task Docs"
                run: "bin/maestro-build-docs"
            - 
                name: "Build Docs"
                uses: ammaraskar/sphinx-action@master
                with:
                    docs-folder: ""
